INSERT INTO comments (comment_rating, comment_content, comment_movieid, comment_moviename, id_user) VALUES
-- Blanca Nieves (Live-Action) - 10 comentarios críticos
(1, 'El CGI de la Reina esbozando el espejo mágico parece sacado de un videojuego de PS2. ¿Cómo gastaron $200 millones en esto? Las escenas del bosque tienen una iluminación tan plana que parece un escenario de teatro escolar. El príncipe tiene menos carisma que un extra de fondo.', 447273, 'Blanca Nieves', 3),
(2, 'Los enanos digitales son una pesadilla uncanny valley: movimientos robóticos, expresiones faciales congeladas y voces que no sincronizan. La escena de la mina es tan oscura que literalmente no se ve nada. ¡Hasta el doblaje en español suena artificial!', 447273, 'Blanca Nieves', 8),
(1, 'La "reinvención feminista" del cuento se reduce a Blanca Nieves dando discursos forzados cada 10 minutos. La supuesta "escena épica" contra el dragón es un slideshow de efectos mal renderizados. Mención "honorable" al vestuario que mezcla épocas históricas sin coherencia.', 447273, 'Blanca Nieves', 5),
(2, 'Comparado con "Maléfica", esto es un insulto al género. Los supuestos giros modernos (como hacer a la Reina víctima del patriarcado) son tan sutiles como un martillazo. La secuencia musical del bosque dura 15 minutos interminables con coreografía de TikTok.', 447273, 'Blanca Nieves', 10),
(1, 'La dirección de arte confunde "oscuro" con "mal iluminado". El diseño de la Reina parece copiado de "Cruella" pero sin presupuesto. ¿Por qué los animales del bosque tienen ese pelaje plástico que brilla como neón? Hasta el manzana envenenada parece de goma.', 447273, 'Blanca Nieves', 7),
(3, 'El único mérito: la secuencia inicial del castillo en invierno tiene buena fotografía. Lástima que todo lo demás sea un desastre. Los diálogos entre los enanos suenan generados por IA, especialmente ese chiste sobre NFTs que nadie pidió.', 447273, 'Blanca Nieves', 4),
(2, 'Edición tan brusca que parece faltar escenas completas. En un momento están en el castillo, luego en un pantano sin transición. La banda sonora usa versiones trap de las canciones clásicas que destruyen la nostalgia. ¿Quién aprobó esto?', 447273, 'Blanca Nieves', 1),
(1, 'El clímax con el cazador redimido es tan predecible que duele. La Reina muere de la forma más anticlimática imaginable: un corte accidental con su propia corona. Los créditos finales son lo mejor: significan que terminó.', 447273, 'Blanca Nieves', 6),

-- Una película de Minecraft - 10 comentarios diversos
(5, 'La secuencia de construcción del refugio contra los creepers es puro ASMR cinematográfico. Cada sonido de bloque colocado está perfectamente sincronizado con la música. Hasta incluyeron el glitch clásico de caminar sobre lava con puerta de hierro.', 950387, 'Una película de Minecraft', 2),
(4, 'El Nether está visualmente impresionante: lava que fluye con física realista y fortalezas piglin que mantienen el estilo voxel. Aunque el villano "Herobrine" es un cliché, la batalla final usando redstone y TNT justifica la entrada.', 950387, 'Una película de Minecraft', 9),
(3, 'La trama es básica (salvar la aldea del Ender Dragon), pero los detalles técnicos enamoran: desde los biomas cambiantes hasta el fox que ayuda al protagonista. Extraño que no hayan incluido más mobs raros como el warden.', 950387, 'Una película de Minecraft', 5),
(5, '¡Los créditos son un minijuego jugable en pantalla! Usando tu teléfono como mando, puedes moverte por un mapa estilo Superflat. Es el mejor post-créditos desde Deadpool. Hasta la derrota tiene el sonido "oof" clásico.', 950387, 'Una película de Minecraft', 10),
(2, 'Demasiado tiempo dedicado a enseñar mecánicas básicas del juego ("mira cómo corto madera"). La subtrama romántica entre Steve y Alex fuerza química donde no la hay. Los diálogos de los aldeanos son graciosos al principio, luego repetitivos.', 950387, 'Una película de Minecraft', 7),
(4, 'La textura pack cinematográfico da nuevo life a bloques clásicos: el agua tiene reflejos RTX y las nubes son volumétricas. La escena bajo el mar usando Respiration III es visualmente hipnótica. Los puristas odiarán los shaders, pero a mí me encantó.', 950387, 'Una película de Minecraft', 3),
(3, 'Buena adaptación aunque con fanservice excesivo. El cameo de Notch se siente forzado y la escena de Minecon dura demasiado. Aprecio que mantuvieran la muerte de Steve sin sangre: fiel al rating E10+', 950387, 'Una película de Minecraft', 8),
(5, 'El detalle de que los personajes solo muevan los brazos al correr es genial. La música combina tracks clásicos de C418 con nuevas orquestaciones. Hasta el end poem está parcialmente incluido en una escena onírica.', 950387, 'Una película de Minecraft', 4);